{"uuid": "0112ad64-302e-45d1-ae69-1dc9221d99c8", "children": ["7971d1a3-168e-4dc0-a16f-3702f518fdcf"], "befores": [{"name": "_xunit_setup_method_fixture_TestEmail", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable\n  (Session info: chrome=127.0.6533.72)\nStacktrace:\n\tGetHandleVerifier [0x00007FF674D69632+30946]\n\t(No symbol) [0x00007FF674D1E3C9]\n\t(No symbol) [0x00007FF674C16E09]\n\t(No symbol) [0x00007FF674C5DE39]\n\t(No symbol) [0x00007FF674C8CA6A]\n\t(No symbol) [0x00007FF674C5BBB6]\n\t(No symbol) [0x00007FF674C8CC80]\n\t(No symbol) [0x00007FF674CAB041]\n\t(No symbol) [0x00007FF674C8C813]\n\t(No symbol) [0x00007FF674C5A6E5]\n\t(No symbol) [0x00007FF674C5B021]\n\tGetHandleVerifier [0x00007FF674E9F83D+1301229]\n\tGetHandleVerifier [0x00007FF674EABDB7+1351783]\n\tGetHandleVerifier [0x00007FF674EA2A03+1313971]\n\tGetHandleVerifier [0x00007FF674D9DD06+245686]\n\t(No symbol) [0x00007FF674D2758F]\n\t(No symbol) [0x00007FF674D23804]\n\t(No symbol) [0x00007FF674D23992]\n\t(No symbol) [0x00007FF674D1A3EF]\n\tBaseThreadInitThunk [0x00007FFABA49257D+29]\n\tRtlUserThreadStart [0x00007FFABA84AF28+40]\n\n", "trace": "  File \"C:\\Users\\hp\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\hp\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"C:\\Users\\hp\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\hp\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 1125, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\hp\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 880, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\hp\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\_pytest\\python.py\", line 820, in xunit_setup_method_fixture\n    _call_with_optional_argument(func, method)\n  File \"C:\\Users\\hp\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\_pytest\\python.py\", line 716, in _call_with_optional_argument\n    func()\n  File \"C:\\Users\\hp\\Desktop\\a工作相关\\163邮箱\\testcase\\test_send_email.py\", line 23, in setup_method\n    self.login_page.login(\"15703070836\", \"Hm12012326\")\n  File \"C:\\Users\\hp\\Desktop\\a工作相关\\163邮箱\\pageobjects\\login_page.py\", line 28, in login\n    self.input_text(email, *self.email_loc)\n  File \"C:\\Users\\hp\\Desktop\\a工作相关\\163邮箱\\common\\BaseView.py\", line 40, in input_text\n    el.clear()\n  File \"C:\\Users\\hp\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 117, in clear\n    self._execute(Command.CLEAR_ELEMENT)\n  File \"C:\\Users\\hp\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 395, in _execute\n    return self._parent.execute(command, params)\n  File \"C:\\Users\\hp\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\hp\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1721976726915, "stop": 1721976729348}], "start": 1721976726915, "stop": 1721976729474}